version: '3.7'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/custom.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "3001:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
