global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: 
          - host.docker.internal:9096
          - host.docker.internal:8091
          - host.docker.internal:8092
          - host.docker.internal:8888
          - host.docker.internal:8086

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:6380
